//! Codex's app-server protocol.
//!
//! JSON-RPC over stdio, with the `jsonrpc` member omitted. Recorded from
//! codex-cli 0.153.4 on 2026-09-15; the recording is
//! `fixtures/codex/hello.jsonl` and the vendor's own schema, generated by
//! `codex app-server generate-json-schema`, is in `fixtures/codex/schema/`.
//!
//! Unlike Claude Code, the handshake chains, so this codec is a small state
//! machine. Each response drives the next request:
//!
//! ```text
//! -> initialize                     id 1
//! <- result                         codexHome, userAgent
//! -> initialized                    notification
//! -> thread/start                   id 2, cwd + sandbox + approvalPolicy
//! <- result                         thread.id, model
//! -> turn/start                     id 3, threadId + input
//! <- turn/started                   turn.id
//! <- item/agentMessage/delta        "Hello" "," " lovely" " human" "."
//! <- item/completed  agentMessage   the whole text, authoritative
//! <- thread/tokenUsage/updated      tokens + modelContextWindow
//! <- turn/completed                 status
//! ```
//!
//! A turn asked for before the thread exists is held and sent when the thread
//! opens, so the engine never has to know the handshake is still in flight.

use std::collections::HashMap;

use kitty_core::{ErrorKind, SessionEvent, StopReason, Usage};
use serde_json::{json, Value};

use crate::{str_field, u64_field, Codec, StartContext, Step};

/// Argv after the resolved binary.
#[must_use]
pub fn launch_args() -> Vec<String> {
    vec!["app-server".to_owned()]
}

/// What we are waiting for a given JSON-RPC id to answer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Pending {
    Initialize,
    ThreadStart,
    TurnStart,
}

#[derive(Default)]
pub struct CodexCodec {
    next_id: u64,
    pending: HashMap<u64, Pending>,
    thread_id: Option<String>,
    turn_id: Option<String>,
    /// A prompt asked for before the thread was ready.
    queued_turn: Option<String>,
    cwd: String,
    resume: Option<String>,
    model: Option<String>,
}

impl CodexCodec {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    fn request(&mut self, method: &str, params: &Value, what: Pending) -> String {
        self.next_id += 1;
        self.pending.insert(self.next_id, what);
        json!({ "id": self.next_id, "method": method, "params": params }).to_string()
    }

    fn turn_start_frame(&mut self, text: &str) -> Option<String> {
        let thread = self.thread_id.clone()?;
        let mut params = json!({
            "threadId": thread,
            "input": [{ "type": "text", "text": text }],
        });
        if let Some(model) = &self.model {
            params["model"] = json!(model);
        }
        Some(self.request("turn/start", &params, Pending::TurnStart))
    }

    /// Opens a thread, or resumes the one we were given.
    fn open_thread(&mut self) -> String {
        let mut params = json!({
            "cwd": self.cwd,
            // Slice 2 streams text and nothing else. A read-only sandbox with
            // no approvals means a turn can never block on a prompt we have
            // nowhere to show yet. Slice 3 widens this.
            "sandbox": "read-only",
            "approvalPolicy": "never",
        });
        if let Some(model) = &self.model {
            params["model"] = json!(model);
        }

        match self.resume.clone() {
            Some(thread) => {
                params["threadId"] = json!(thread);
                self.request("thread/resume", &params, Pending::ThreadStart)
            }
            None => self.request("thread/start", &params, Pending::ThreadStart),
        }
    }
}

impl Codec for CodexCodec {
    fn start(&mut self, ctx: &StartContext) -> Step {
        self.cwd.clone_from(&ctx.cwd);
        self.resume.clone_from(&ctx.resume);
        self.model.clone_from(&ctx.model);

        let line = self.request(
            "initialize",
            &json!({
                "clientInfo": { "name": "kitty", "title": "kitty", "version": env!("CARGO_PKG_VERSION") },
                "capabilities": { "experimentalApi": true },
            }),
            Pending::Initialize,
        );
        Step::send(line)
    }

    fn send_turn(&mut self, text: &str) -> Step {
        if let Some(line) = self.turn_start_frame(text) {
            return Step::send(line);
        }
        // The handshake is still running. Hold it; `on_frame` sends it the
        // moment the thread opens.
        self.queued_turn = Some(text.to_owned());
        Step::none()
    }

    fn cancel(&mut self) -> Step {
        let (Some(thread), Some(turn)) = (self.thread_id.clone(), self.turn_id.clone()) else {
            // Nothing running. Drop any prompt that never made it out, so it
            // does not fire after the user asked to stop.
            self.queued_turn = None;
            return Step::none();
        };
        self.next_id += 1;
        Step::send(
            json!({
                "id": self.next_id,
                "method": "turn/interrupt",
                "params": { "threadId": thread, "turnId": turn },
            })
            .to_string(),
        )
    }

    fn on_frame(&mut self, line: &str) -> Step {
        let Ok(msg) = serde_json::from_str::<Value>(line) else {
            return Step::none();
        };

        if let Some(id) = msg.get("id").and_then(Value::as_u64) {
            if msg.get("result").is_some() || msg.get("error").is_some() {
                return self.on_response(id, &msg);
            }
            // A server-initiated request. Approvals arrive this way and are
            // slice 3's problem; the read-only sandbox means none should come.
            return Step::none();
        }

        match str_field(&msg, "method") {
            Some(method) => self.on_notification(method, msg.get("params")),
            None => Step::none(),
        }
    }
}

impl CodexCodec {
    fn on_response(&mut self, id: u64, msg: &Value) -> Step {
        let Some(what) = self.pending.remove(&id) else {
            return Step::none();
        };

        if let Some(error) = msg.get("error") {
            let message = str_field(error, "message")
                .unwrap_or("the app-server rejected a request")
                .to_owned();
            return Step::event(SessionEvent::Error {
                error_kind: classify(&message),
                message,
                retryable: false,
            });
        }

        let result = msg.get("result").unwrap_or(&Value::Null);

        match what {
            Pending::Initialize => {
                let ready = self.open_thread();
                Step::send(json!({ "method": "initialized" }).to_string()).with_send(ready)
            }

            Pending::ThreadStart => {
                let thread = result.get("thread");
                let id = thread
                    .and_then(|t| str_field(t, "id"))
                    .or_else(|| str_field(result, "threadId"))
                    .map(str::to_owned);
                let model = str_field(result, "model")
                    .or_else(|| thread.and_then(|t| str_field(t, "model")))
                    .map(str::to_owned);

                self.thread_id.clone_from(&id);

                let mut step = Step::event(SessionEvent::Started {
                    provider_session: id,
                    model,
                });
                if let Some(text) = self.queued_turn.take() {
                    if let Some(line) = self.turn_start_frame(&text) {
                        step.send.push(line);
                    }
                }
                step
            }

            // `turn/started` carries the id we need; the response adds nothing.
            Pending::TurnStart => Step::none(),
        }
    }

    fn on_notification(&mut self, method: &str, params: Option<&Value>) -> Step {
        let params = params.unwrap_or(&Value::Null);

        match method {
            "thread/started" => {
                if self.thread_id.is_none() {
                    self.thread_id = params
                        .get("thread")
                        .and_then(|t| str_field(t, "id"))
                        .map(str::to_owned);
                }
                Step::none()
            }

            "turn/started" => {
                self.turn_id = params
                    .get("turn")
                    .and_then(|t| str_field(t, "id"))
                    .map(str::to_owned);
                Step::event(SessionEvent::TurnStarted)
            }

            "item/agentMessage/delta" => {
                str_field(params, "delta").map_or_else(Step::none, |text| {
                    Step::event(SessionEvent::MessageDelta {
                        text: text.to_owned(),
                    })
                })
            }

            "item/reasoning/summaryTextDelta" | "item/reasoning/textDelta" => {
                str_field(params, "delta").map_or_else(Step::none, |text| {
                    Step::event(SessionEvent::ReasoningDelta {
                        text: text.to_owned(),
                    })
                })
            }

            "item/completed" => {
                let item = params.get("item").unwrap_or(&Value::Null);
                match str_field(item, "type") {
                    Some("agentMessage") => {
                        let text = str_field(item, "text").unwrap_or_default();
                        if text.is_empty() {
                            return Step::none();
                        }
                        Step::event(SessionEvent::MessageDone {
                            text: text.to_owned(),
                        })
                    }
                    Some("reasoning") => Step::event(SessionEvent::ReasoningDone),
                    _ => Step::none(),
                }
            }

            "thread/tokenUsage/updated" => on_token_usage(params),

            "turn/completed" => {
                self.turn_id = None;
                let turn = params.get("turn").unwrap_or(&Value::Null);
                Step::event(SessionEvent::TurnEnded {
                    stop: stop_reason_from(turn),
                })
            }

            "error" => {
                let message = str_field(params, "message")
                    .unwrap_or("the CLI reported an error")
                    .to_owned();
                Step::event(SessionEvent::Error {
                    error_kind: classify(&message),
                    message,
                    retryable: false,
                })
            }

            "warning" | "configWarning" | "deprecationNotice" => str_field(params, "message")
                .map_or_else(Step::none, |text| {
                    Step::event(SessionEvent::Status {
                        text: text.to_owned(),
                    })
                }),

            _ => Step::none(),
        }
    }
}

fn stop_reason_from(turn: &Value) -> StopReason {
    if let Some(error) = turn.get("error").filter(|e| !e.is_null()) {
        return StopReason::Failed {
            message: str_field(error, "message")
                .unwrap_or("the turn failed")
                .to_owned(),
        };
    }
    match str_field(turn, "status") {
        Some("completed") | None => StopReason::EndTurn,
        Some("aborted" | "cancelled" | "interrupted") => StopReason::Cancelled,
        Some(other) => StopReason::Other {
            reason: other.to_owned(),
        },
    }
}

/// Reads the per-turn token counts and the context-window level.
///
/// Uses `last`, not `total`. `MonoCode` records the reason in a comment and it
/// is correct: `total` keeps climbing across compactions and would eventually
/// report more than a full context window.
fn on_token_usage(params: &Value) -> Step {
    let Some(usage) = params.get("tokenUsage") else {
        return Step::none();
    };
    let last = usage.get("last").unwrap_or(&Value::Null);

    let mut step = Step::event(SessionEvent::Usage(Usage {
        input_tokens: u64_field(last, "inputTokens").unwrap_or(0),
        output_tokens: u64_field(last, "outputTokens").unwrap_or(0),
        cache_read_tokens: u64_field(last, "cachedInputTokens").unwrap_or(0),
        cache_write_tokens: u64_field(last, "cacheWriteInputTokens").unwrap_or(0),
        reasoning_tokens: u64_field(last, "reasoningOutputTokens").unwrap_or(0),
    }));

    let window = u64_field(usage, "modelContextWindow");
    let used = u64_field(last, "totalTokens");
    if window.is_some() || used.is_some() {
        step.events.push(SessionEvent::Context { used, window });
    }
    step
}

#[must_use]
pub fn classify(message: &str) -> ErrorKind {
    let lower = message.to_ascii_lowercase();
    if lower.contains("rate limit") || lower.contains("quota") || lower.contains("429") {
        ErrorKind::RateLimited
    } else if lower.contains("auth") || lower.contains("log in") || lower.contains("401") {
        ErrorKind::Auth
    } else {
        ErrorKind::Transient
    }
}

#[cfg(test)]
mod tests {
    use super::{launch_args, CodexCodec};
    use crate::{Codec, StartContext, Step};
    use kitty_core::{SessionEvent, StopReason};
    use serde_json::{json, Value};

    fn ctx() -> StartContext {
        StartContext {
            cwd: r"C:\work".into(),
            resume: None,
            model: None,
        }
    }

    // Taking the value by move keeps every call site a bare `json!(...)`.
    #[allow(clippy::needless_pass_by_value)]
    fn feed(codec: &mut CodexCodec, value: Value) -> Step {
        codec.on_frame(&value.to_string())
    }

    fn parse(line: &str) -> Value {
        serde_json::from_str(line).expect("frames must be valid JSON")
    }

    /// Runs the handshake and returns the events it produced.
    fn handshake(codec: &mut CodexCodec) -> Vec<SessionEvent> {
        let start = codec.start(&ctx());
        let init = parse(&start.send[0]);
        assert_eq!(init["method"], "initialize");

        let after_init = feed(
            codec,
            json!({"id": init["id"], "result": {"userAgent": "codex/0.153.4"}}),
        );
        assert_eq!(parse(&after_init.send[0])["method"], "initialized");
        let open = parse(&after_init.send[1]);
        assert_eq!(open["method"], "thread/start");

        let ready = feed(
            codec,
            json!({"id": open["id"], "result": {
                "model": "gpt-5.6-terra",
                "thread": {"id": "thread-1", "model": "gpt-5.6-terra"}}}),
        );
        ready.events
    }

    #[test]
    fn launch_args_are_just_the_subcommand() {
        assert_eq!(launch_args(), vec!["app-server".to_owned()]);
    }

    #[test]
    fn the_handshake_chains_to_a_ready_thread() {
        let mut codec = CodexCodec::new();
        let events = handshake(&mut codec);
        assert_eq!(
            events,
            vec![SessionEvent::Started {
                provider_session: Some("thread-1".into()),
                model: Some("gpt-5.6-terra".into()),
            }]
        );
    }

    #[test]
    fn a_turn_asked_for_early_is_held_until_the_thread_opens() {
        let mut codec = CodexCodec::new();
        let start = codec.start(&ctx());
        let init = parse(&start.send[0]);

        // The user hits send while we are still shaking hands.
        assert!(codec.send_turn("hello").is_empty());

        let after_init = feed(
            codec_ref(&mut codec),
            json!({"id": init["id"], "result": {}}),
        );
        let open = parse(&after_init.send[1]);

        let ready = feed(
            &mut codec,
            json!({"id": open["id"], "result": {"thread": {"id": "t"}}}),
        );
        let turn = parse(ready.send.last().expect("the held turn must be sent"));
        assert_eq!(turn["method"], "turn/start");
        assert_eq!(turn["params"]["input"][0]["text"], "hello");
    }

    fn codec_ref(codec: &mut CodexCodec) -> &mut CodexCodec {
        codec
    }

    #[test]
    fn resume_reopens_the_named_thread() {
        let mut codec = CodexCodec::new();
        let start = codec.start(&StartContext {
            cwd: r"C:\work".into(),
            resume: Some("thread-7".into()),
            model: None,
        });
        let init = parse(&start.send[0]);
        let after = feed(&mut codec, json!({"id": init["id"], "result": {}}));
        let open = parse(&after.send[1]);
        assert_eq!(open["method"], "thread/resume");
        assert_eq!(open["params"]["threadId"], "thread-7");
    }

    #[test]
    fn deltas_pass_through_untouched_including_leading_spaces() {
        let mut codec = CodexCodec::new();
        handshake(&mut codec);

        let mut text = String::new();
        for chunk in ["Hello", ",", " lovely", " human", "."] {
            let step = feed(
                &mut codec,
                json!({"method": "item/agentMessage/delta",
                       "params": {"threadId": "thread-1", "delta": chunk}}),
            );
            match step.events.as_slice() {
                [SessionEvent::MessageDelta { text: t }] => text.push_str(t),
                other => panic!("expected one delta, got {other:?}"),
            }
        }
        assert_eq!(text, "Hello, lovely human.");
    }

    #[test]
    fn item_completed_is_the_authoritative_text() {
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "item/completed", "params": {"item": {
                "type": "agentMessage", "id": "m1", "text": "Hello, lovely human."}}}),
        );
        assert_eq!(
            step.events,
            vec![SessionEvent::MessageDone {
                text: "Hello, lovely human.".into()
            }]
        );
    }

    #[test]
    fn an_empty_agent_message_start_produces_nothing() {
        // `item/started` for an agentMessage carries an empty text.
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "item/completed", "params": {"item": {
                "type": "agentMessage", "text": ""}}}),
        );
        assert!(step.is_empty());
    }

    #[test]
    fn token_usage_reports_the_last_turn_not_the_running_total() {
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "thread/tokenUsage/updated", "params": {"tokenUsage": {
                "total": {"totalTokens": 999_999, "inputTokens": 999_999},
                "last": {"totalTokens": 16325, "inputTokens": 16316, "outputTokens": 9,
                         "cachedInputTokens": 12032, "reasoningOutputTokens": 0},
                "modelContextWindow": 258_400}}}),
        );
        match step.events.as_slice() {
            [SessionEvent::Usage(usage), SessionEvent::Context { used, window }] => {
                assert_eq!(usage.input_tokens, 16316, "must use `last`, not `total`");
                assert_eq!(usage.cache_read_tokens, 12032);
                assert_eq!(*used, Some(16325));
                assert_eq!(*window, Some(258_400));
            }
            other => panic!("unexpected events: {other:?}"),
        }
    }

    #[test]
    fn turn_completed_ends_the_turn() {
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "turn/completed",
                   "params": {"turn": {"id": "t1", "status": "completed", "error": null}}}),
        );
        assert_eq!(
            step.events,
            vec![SessionEvent::TurnEnded {
                stop: StopReason::EndTurn
            }]
        );
    }

    #[test]
    fn an_aborted_turn_reads_as_cancelled() {
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "turn/completed", "params": {"turn": {"status": "aborted"}}}),
        );
        assert_eq!(
            step.events,
            vec![SessionEvent::TurnEnded {
                stop: StopReason::Cancelled
            }]
        );
    }

    #[test]
    fn a_failed_turn_carries_its_message() {
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "turn/completed", "params": {"turn": {
                "status": "failed", "error": {"message": "model unavailable"}}}}),
        );
        assert!(matches!(
            step.events.first(),
            Some(SessionEvent::TurnEnded { stop: StopReason::Failed { message } })
                if message == "model unavailable"
        ));
    }

    #[test]
    fn cancel_interrupts_the_running_turn() {
        let mut codec = CodexCodec::new();
        handshake(&mut codec);
        feed(
            &mut codec,
            json!({"method": "turn/started", "params": {"turn": {"id": "turn-9"}}}),
        );

        let step = codec.cancel();
        let sent = parse(&step.send[0]);
        assert_eq!(sent["method"], "turn/interrupt");
        assert_eq!(sent["params"]["threadId"], "thread-1");
        assert_eq!(sent["params"]["turnId"], "turn-9");
    }

    #[test]
    fn cancelling_before_a_turn_starts_drops_the_queued_prompt() {
        let mut codec = CodexCodec::new();
        codec.start(&ctx());
        codec.send_turn("do not send me");
        assert!(codec.cancel().is_empty());
        assert!(
            codec.queued_turn.is_none(),
            "the queued prompt must be dropped"
        );
    }

    #[test]
    fn a_rejected_request_becomes_an_error_event() {
        let mut codec = CodexCodec::new();
        let start = codec.start(&ctx());
        let init = parse(&start.send[0]);
        let step = feed(
            &mut codec,
            json!({"id": init["id"], "error": {"code": -32600, "message": "not authenticated"}}),
        );
        assert!(matches!(
            step.events.first(),
            Some(SessionEvent::Error { error_kind, .. })
                if *error_kind == kitty_core::ErrorKind::Auth
        ));
    }

    #[test]
    fn garbage_is_ignored_rather_than_fatal() {
        let mut codec = CodexCodec::new();
        assert!(codec.on_frame("not json").is_empty());
        assert!(codec.on_frame("{}").is_empty());
        assert!(codec.on_frame(r#"{"method":"something/new"}"#).is_empty());
        assert!(codec.on_frame(r#"{"id":999,"result":{}}"#).is_empty());
    }
}
