//! Codex's app-server protocol.
//!
//! JSON-RPC over stdio, with the `jsonrpc` member omitted. Recorded from
//! codex-cli 0.153.4 on 2026-09-15; the recording is
//! `fixtures/codex/hello.jsonl` and the vendor's own schema, generated by
//! `codex app-server generate-json-schema`, is in `fixtures/codex/schema/`.
//!
//! Unlike Claude Code, the handshake chains, so this codec is a small state
//! machine. Each response drives the next request:
//!
//! ```text
//! -> initialize                     id 1
//! <- result                         codexHome, userAgent
//! -> initialized                    notification
//! -> thread/start                   id 2, cwd + sandbox + approvalPolicy
//! <- result                         thread.id, model
//! -> turn/start                     id 3, threadId + input
//! <- turn/started                   turn.id
//! <- item/agentMessage/delta        "Hello" "," " lovely" " human" "."
//! <- item/completed  agentMessage   the whole text, authoritative
//! <- thread/tokenUsage/updated      tokens + modelContextWindow
//! <- turn/completed                 status
//! ```
//!
//! A turn asked for before the thread exists is held and sent when the thread
//! opens, so the engine never has to know the handshake is still in flight.

use std::collections::HashMap;

use kitty_core::{
    ApprovalKind, ApprovalOutcome, ErrorKind, RateLimitWindow, SessionEvent, StopReason,
    ToolStatus, Usage,
};
use serde_json::{json, Value};

use crate::{first_line, short_path, str_field, u64_field, Codec, StartContext, Step};

/// Argv after the resolved binary.
#[must_use]
pub fn launch_args() -> Vec<String> {
    vec!["app-server".to_owned()]
}

/// What we are waiting for a given JSON-RPC id to answer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Pending {
    Initialize,
    ThreadStart,
    TurnStart,
}

#[derive(Default)]
pub struct CodexCodec {
    next_id: u64,
    pending: HashMap<u64, Pending>,
    thread_id: Option<String>,
    turn_id: Option<String>,
    /// A prompt asked for before the thread was ready.
    queued_turn: Option<String>,
    /// Pending permission requests, by the id we handed upwards, to the
    /// JSON-RPC id the server is waiting on.
    approvals: HashMap<String, u64>,
    /// Tool items in flight, so a completion can be matched to its row.
    tools: HashMap<String, String>,
    cwd: String,
    resume: Option<String>,
    model: Option<String>,
    effort: Option<String>,
}

impl CodexCodec {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    fn request(&mut self, method: &str, params: &Value, what: Pending) -> String {
        self.next_id += 1;
        self.pending.insert(self.next_id, what);
        json!({ "id": self.next_id, "method": method, "params": params }).to_string()
    }

    fn turn_start_frame(&mut self, text: &str) -> Option<String> {
        let thread = self.thread_id.clone()?;
        let mut params = json!({
            "threadId": thread,
            "input": [{ "type": "text", "text": text }],
        });
        if let Some(model) = &self.model {
            params["model"] = json!(model);
        }
        // Effort belongs to the turn, not the thread, so changing it mid
        // conversation needs no new thread.
        if let Some(effort) = &self.effort {
            params["effort"] = json!(effort);
        }
        Some(self.request("turn/start", &params, Pending::TurnStart))
    }

    /// Opens a thread, or resumes the one we were given.
    fn open_thread(&mut self) -> String {
        let mut params = json!({
            "cwd": self.cwd,
            // Read-only plus on-request is what makes the CLI escalate to
            // us rather than deciding alone. Widening the sandbox is a later
            // per-session setting; asking is the safe default.
            "sandbox": "read-only",
            "approvalPolicy": "on-request",
        });
        if let Some(model) = &self.model {
            params["model"] = json!(model);
        }

        match self.resume.clone() {
            Some(thread) => {
                params["threadId"] = json!(thread);
                self.request("thread/resume", &params, Pending::ThreadStart)
            }
            None => self.request("thread/start", &params, Pending::ThreadStart),
        }
    }
}

impl Codec for CodexCodec {
    fn start(&mut self, ctx: &StartContext) -> Step {
        self.cwd.clone_from(&ctx.cwd);
        self.resume.clone_from(&ctx.resume);
        self.model.clone_from(&ctx.model);
        self.effort.clone_from(&ctx.effort);

        let line = self.request(
            "initialize",
            &json!({
                "clientInfo": { "name": "kitty", "title": "kitty", "version": env!("CARGO_PKG_VERSION") },
                "capabilities": { "experimentalApi": true },
            }),
            Pending::Initialize,
        );
        Step::send(line)
    }

    fn send_turn(&mut self, text: &str) -> Step {
        if let Some(line) = self.turn_start_frame(text) {
            return Step::send(line);
        }
        // The handshake is still running. Hold it; `on_frame` sends it the
        // moment the thread opens.
        self.queued_turn = Some(text.to_owned());
        Step::none()
    }

    fn respond_approval(&mut self, id: &str, allow: bool) -> Step {
        let Some(request_id) = self.approvals.remove(id) else {
            // Already settled, or never ours. Answering twice would confuse
            // the server far more than staying quiet.
            return Step::none();
        };

        // `item/permissions/requestApproval` wants the permission set echoed
        // back; the others take a decision. Declining is expressed the same
        // way for both, so only the accept path differs.
        let result = if allow {
            json!({ "decision": "accept" })
        } else {
            json!({ "decision": "decline" })
        };
        Step::send(json!({ "id": request_id, "result": result }).to_string())
    }

    fn cancel(&mut self) -> Step {
        let (Some(thread), Some(turn)) = (self.thread_id.clone(), self.turn_id.clone()) else {
            // Nothing running. Drop any prompt that never made it out, so it
            // does not fire after the user asked to stop.
            self.queued_turn = None;
            return Step::none();
        };
        self.next_id += 1;
        Step::send(
            json!({
                "id": self.next_id,
                "method": "turn/interrupt",
                "params": { "threadId": thread, "turnId": turn },
            })
            .to_string(),
        )
    }

    fn on_frame(&mut self, line: &str) -> Step {
        let Ok(msg) = serde_json::from_str::<Value>(line) else {
            return Step::none();
        };

        if let Some(id) = msg.get("id").and_then(Value::as_u64) {
            if msg.get("result").is_some() || msg.get("error").is_some() {
                return self.on_response(id, &msg);
            }
            // A server-initiated request: it carries both an id and a
            // method. Approvals arrive this way.
            return self.on_server_request(id, &msg);
        }

        match str_field(&msg, "method") {
            Some(method) => self.on_notification(method, msg.get("params")),
            None => Step::none(),
        }
    }
}

impl CodexCodec {
    fn on_response(&mut self, id: u64, msg: &Value) -> Step {
        let Some(what) = self.pending.remove(&id) else {
            return Step::none();
        };

        if let Some(error) = msg.get("error") {
            let message = str_field(error, "message")
                .unwrap_or("the app-server rejected a request")
                .to_owned();
            return Step::event(SessionEvent::Error {
                error_kind: classify(&message),
                message,
                retryable: false,
            });
        }

        let result = msg.get("result").unwrap_or(&Value::Null);

        match what {
            Pending::Initialize => {
                let ready = self.open_thread();
                Step::send(json!({ "method": "initialized" }).to_string()).with_send(ready)
            }

            Pending::ThreadStart => {
                let thread = result.get("thread");
                let id = thread
                    .and_then(|t| str_field(t, "id"))
                    .or_else(|| str_field(result, "threadId"))
                    .map(str::to_owned);
                let model = str_field(result, "model")
                    .or_else(|| thread.and_then(|t| str_field(t, "model")))
                    .map(str::to_owned);

                self.thread_id.clone_from(&id);

                let mut step = Step::event(SessionEvent::Started {
                    provider_session: id,
                    model,
                });
                if let Some(text) = self.queued_turn.take() {
                    if let Some(line) = self.turn_start_frame(&text) {
                        step.send.push(line);
                    }
                }
                step
            }

            // `turn/started` carries the id we need; the response adds nothing.
            Pending::TurnStart => Step::none(),
        }
    }

    fn on_notification(&mut self, method: &str, params: Option<&Value>) -> Step {
        let params = params.unwrap_or(&Value::Null);

        match method {
            "thread/started" => {
                if self.thread_id.is_none() {
                    self.thread_id = params
                        .get("thread")
                        .and_then(|t| str_field(t, "id"))
                        .map(str::to_owned);
                }
                Step::none()
            }

            "turn/started" => {
                self.turn_id = params
                    .get("turn")
                    .and_then(|t| str_field(t, "id"))
                    .map(str::to_owned);
                Step::event(SessionEvent::TurnStarted)
            }

            "item/agentMessage/delta" => {
                str_field(params, "delta").map_or_else(Step::none, |text| {
                    Step::event(SessionEvent::MessageDelta {
                        text: text.to_owned(),
                    })
                })
            }

            "item/reasoning/summaryTextDelta" | "item/reasoning/textDelta" => {
                str_field(params, "delta").map_or_else(Step::none, |text| {
                    Step::event(SessionEvent::ReasoningDelta {
                        text: text.to_owned(),
                    })
                })
            }

            "item/started" => self.on_item(params, false),
            "item/completed" => self.on_item(params, true),

            "serverRequest/resolved" => {
                // Someone else answered, or the turn ended first. A real third
                // outcome, not a synonym for denied.
                let id = format!(
                    "codex-{}",
                    params
                        .get("requestId")
                        .and_then(Value::as_u64)
                        .unwrap_or_default()
                );
                if self.approvals.remove(&id).is_some() {
                    return Step::event(SessionEvent::ApprovalResolved {
                        id,
                        outcome: ApprovalOutcome::Cancelled,
                    });
                }
                Step::none()
            }

            "thread/tokenUsage/updated" => on_token_usage(params),

            "account/rateLimits/updated" => on_rate_limits(params),

            "turn/completed" => {
                self.turn_id = None;
                let turn = params.get("turn").unwrap_or(&Value::Null);
                Step::event(SessionEvent::TurnEnded {
                    stop: stop_reason_from(turn),
                })
            }

            "error" => {
                let message = str_field(params, "message")
                    .unwrap_or("the CLI reported an error")
                    .to_owned();
                Step::event(SessionEvent::Error {
                    error_kind: classify(&message),
                    message,
                    retryable: false,
                })
            }

            "warning" | "configWarning" | "deprecationNotice" => str_field(params, "message")
                .map_or_else(Step::none, |text| {
                    Step::event(SessionEvent::Status {
                        text: text.to_owned(),
                    })
                }),

            _ => Step::none(),
        }
    }
}

impl CodexCodec {
    /// A request the server is blocking on until we answer.
    fn on_server_request(&mut self, request_id: u64, msg: &Value) -> Step {
        let method = str_field(msg, "method").unwrap_or_default();
        let params = msg.get("params").unwrap_or(&Value::Null);

        let approval_kind = match method {
            "item/fileChange/requestApproval" | "applyPatchApproval" => ApprovalKind::Edit,
            "item/commandExecution/requestApproval" | "execCommandApproval" => {
                ApprovalKind::Command
            }
            // A permissions request, and anything we do not recognise, still
            // reaches the user. A request nobody answers stalls the turn, so
            // an unknown one must never be silently dropped.
            _ => ApprovalKind::Other,
        };

        let id = format!("codex-{request_id}");
        self.approvals.insert(id.clone(), request_id);

        // The request names an item rather than repeating its details, so the
        // title comes from the row we already announced.
        let title = str_field(params, "itemId")
            .and_then(|item| self.tools.get(item).cloned())
            .or_else(|| str_field(params, "command").map(|c| first_line(c, 80)))
            .unwrap_or_else(|| match approval_kind {
                ApprovalKind::Edit => "Edit files".to_owned(),
                ApprovalKind::Command => "Run a command".to_owned(),
                _ => "Continue".to_owned(),
            });

        Step::event(SessionEvent::ApprovalRequested {
            id,
            approval_kind,
            title,
            detail: str_field(params, "reason").map(|r| first_line(r, 200)),
        })
    }

    /// Routes an item notification by what kind of item it is.
    ///
    /// Codex models everything as an item: text, reasoning and tool calls all
    /// arrive through the same two notifications.
    fn on_item(&mut self, params: &Value, finished: bool) -> Step {
        let item = params.get("item").unwrap_or(&Value::Null);
        let kind = str_field(item, "type").unwrap_or_default();

        if is_tool_item(kind) {
            return self.on_tool_item(item, finished);
        }
        if !finished {
            return Step::none();
        }

        match kind {
            "agentMessage" => {
                let text = str_field(item, "text").unwrap_or_default();
                if text.is_empty() {
                    return Step::none();
                }
                Step::event(SessionEvent::MessageDone {
                    text: text.to_owned(),
                })
            }
            "reasoning" => Step::event(SessionEvent::ReasoningDone),
            _ => Step::none(),
        }
    }

    /// A tool item starting or finishing.
    fn on_tool_item(&mut self, item: &Value, finished: bool) -> Step {
        let Some(id) = str_field(item, "id") else {
            return Step::none();
        };
        let kind = str_field(item, "type").unwrap_or_default();

        if !finished {
            let title = tool_title(kind, item);
            self.tools.insert(id.to_owned(), title.clone());
            return Step::event(SessionEvent::ToolStarted {
                call_id: id.to_owned(),
                name: kind.to_owned(),
                title,
            });
        }

        self.tools.remove(id);
        let status = match str_field(item, "status") {
            Some("declined" | "rejected") => ToolStatus::Denied,
            Some("failed" | "error") => ToolStatus::Failed,
            // "completed", and anything that finished without saying how.
            // Absence of a status is not evidence of failure.
            _ => ToolStatus::Ok,
        };
        Step::event(SessionEvent::ToolEnded {
            call_id: id.to_owned(),
            status,
            detail: tool_detail(kind, item),
        })
    }
}

/// Every item type that represents work rather than words.
fn is_tool_item(kind: &str) -> bool {
    matches!(
        kind,
        "fileChange"
            | "commandExecution"
            | "mcpToolCall"
            | "webSearch"
            | "collabAgentToolCall"
            | "subAgentActivity"
    )
}

fn tool_title(kind: &str, item: &Value) -> String {
    match kind {
        "fileChange" => {
            let changes = item.get("changes").and_then(Value::as_array);
            let first = changes.and_then(|c| c.first());
            let path = first.and_then(|c| str_field(c, "path"));
            let verb = first
                .and_then(|c| c.get("kind"))
                .and_then(|k| str_field(k, "type"))
                .map_or("Change", |t| match t {
                    "add" => "Create",
                    "delete" => "Delete",
                    _ => "Edit",
                });
            let count = changes.map_or(0, Vec::len);
            match (path, count) {
                (Some(path), 1) => format!("{verb} {}", short_path(path)),
                (Some(path), n) => format!("{verb} {} and {} more", short_path(path), n - 1),
                _ => verb.to_owned(),
            }
        }
        "commandExecution" => str_field(item, "command")
            .map_or_else(|| "Run a command".to_owned(), |c| first_line(c, 80)),
        "webSearch" => str_field(item, "query")
            .map_or_else(|| "Web search".to_owned(), |q| format!("Search: {q}")),
        "mcpToolCall" => {
            let server = str_field(item, "server").unwrap_or("mcp");
            let tool = str_field(item, "tool").unwrap_or("tool");
            format!("{server}/{tool}")
        }
        other => other.to_owned(),
    }
}

fn tool_detail(kind: &str, item: &Value) -> Option<String> {
    match kind {
        "commandExecution" => str_field(item, "aggregatedOutput")
            .or_else(|| str_field(item, "output"))
            .map(|o| first_line(o, 160)),
        "fileChange" => {
            let count = item
                .get("changes")
                .and_then(Value::as_array)
                .map_or(0, Vec::len);
            (count > 0).then(|| format!("{count} file{}", if count == 1 { "" } else { "s" }))
        }
        _ => None,
    }
}

fn stop_reason_from(turn: &Value) -> StopReason {
    if let Some(error) = turn.get("error").filter(|e| !e.is_null()) {
        return StopReason::Failed {
            message: str_field(error, "message")
                .unwrap_or("the turn failed")
                .to_owned(),
        };
    }
    match str_field(turn, "status") {
        Some("completed") | None => StopReason::EndTurn,
        Some("aborted" | "cancelled" | "interrupted") => StopReason::Cancelled,
        Some(other) => StopReason::Other {
            reason: other.to_owned(),
        },
    }
}

/// Reads the per-turn token counts and the context-window level.
///
/// Uses `last`, not `total`. `MonoCode` records the reason in a comment and it
/// is correct: `total` keeps climbing across compactions and would eventually
/// report more than a full context window.
fn on_token_usage(params: &Value) -> Step {
    let Some(usage) = params.get("tokenUsage") else {
        return Step::none();
    };
    let last = usage.get("last").unwrap_or(&Value::Null);

    let mut step = Step::event(SessionEvent::Usage(Usage {
        input_tokens: u64_field(last, "inputTokens").unwrap_or(0),
        output_tokens: u64_field(last, "outputTokens").unwrap_or(0),
        cache_read_tokens: u64_field(last, "cachedInputTokens").unwrap_or(0),
        cache_write_tokens: u64_field(last, "cacheWriteInputTokens").unwrap_or(0),
        reasoning_tokens: u64_field(last, "reasoningOutputTokens").unwrap_or(0),
    }));

    let window = u64_field(usage, "modelContextWindow");
    let used = u64_field(last, "totalTokens");
    if window.is_some() || used.is_some() {
        step.events.push(SessionEvent::Context { used, window });
    }
    step
}

/// Subscription usage, which Codex pushes unprompted like Claude does.
///
/// Windows are described by duration rather than name, so the label is derived
/// from `windowDurationMins`: 10080 minutes is the weekly window.
fn on_rate_limits(params: &Value) -> Step {
    let Some(limits) = params.get("rateLimits") else {
        return Step::none();
    };

    let windows: Vec<RateLimitWindow> = ["primary", "secondary"]
        .into_iter()
        .filter_map(|slot| limits.get(slot))
        .filter(|value| !value.is_null())
        .filter_map(|window| {
            let used = u64_field(window, "usedPercent")?;
            Some(RateLimitWindow {
                label: window_label(u64_field(window, "windowDurationMins")),
                #[allow(clippy::cast_precision_loss)]
                utilization: used as f64 / 100.0,
                resets_at_ms: window
                    .get("resetsAt")
                    .and_then(Value::as_i64)
                    .and_then(|s| s.checked_mul(1000)),
            })
        })
        .collect();

    if windows.is_empty() {
        return Step::none();
    }
    Step::event(SessionEvent::RateLimits { windows })
}

/// Turns a window duration into something short enough for a status line.
fn window_label(minutes: Option<u64>) -> String {
    match minutes {
        Some(m) if m >= 1440 && m % 1440 == 0 => format!("{}d", m / 1440),
        Some(m) if m >= 60 && m % 60 == 0 => format!("{}h", m / 60),
        Some(m) => format!("{m}m"),
        None => "usage".to_owned(),
    }
}

#[must_use]
pub fn classify(message: &str) -> ErrorKind {
    let lower = message.to_ascii_lowercase();
    if lower.contains("rate limit") || lower.contains("quota") || lower.contains("429") {
        ErrorKind::RateLimited
    } else if lower.contains("auth") || lower.contains("log in") || lower.contains("401") {
        ErrorKind::Auth
    } else {
        ErrorKind::Transient
    }
}

#[cfg(test)]
mod tests {
    use super::{launch_args, CodexCodec};
    use crate::{Codec, StartContext, Step};
    use kitty_core::{SessionEvent, StopReason};
    use serde_json::{json, Value};

    fn ctx() -> StartContext {
        StartContext {
            cwd: r"C:\work".into(),
            resume: None,
            model: None,
            effort: None,
        }
    }

    // Taking the value by move keeps every call site a bare `json!(...)`.
    #[allow(clippy::needless_pass_by_value)]
    fn feed(codec: &mut CodexCodec, value: Value) -> Step {
        codec.on_frame(&value.to_string())
    }

    fn parse(line: &str) -> Value {
        serde_json::from_str(line).expect("frames must be valid JSON")
    }

    /// Runs the handshake and returns the events it produced.
    fn handshake(codec: &mut CodexCodec) -> Vec<SessionEvent> {
        let start = codec.start(&ctx());
        let init = parse(&start.send[0]);
        assert_eq!(init["method"], "initialize");

        let after_init = feed(
            codec,
            json!({"id": init["id"], "result": {"userAgent": "codex/0.153.4"}}),
        );
        assert_eq!(parse(&after_init.send[0])["method"], "initialized");
        let open = parse(&after_init.send[1]);
        assert_eq!(open["method"], "thread/start");

        let ready = feed(
            codec,
            json!({"id": open["id"], "result": {
                "model": "gpt-5.6-terra",
                "thread": {"id": "thread-1", "model": "gpt-5.6-terra"}}}),
        );
        ready.events
    }

    #[test]
    fn launch_args_are_just_the_subcommand() {
        assert_eq!(launch_args(), vec!["app-server".to_owned()]);
    }

    #[test]
    fn the_handshake_chains_to_a_ready_thread() {
        let mut codec = CodexCodec::new();
        let events = handshake(&mut codec);
        assert_eq!(
            events,
            vec![SessionEvent::Started {
                provider_session: Some("thread-1".into()),
                model: Some("gpt-5.6-terra".into()),
            }]
        );
    }

    #[test]
    fn a_turn_asked_for_early_is_held_until_the_thread_opens() {
        let mut codec = CodexCodec::new();
        let start = codec.start(&ctx());
        let init = parse(&start.send[0]);

        // The user hits send while we are still shaking hands.
        assert!(codec.send_turn("hello").is_empty());

        let after_init = feed(
            codec_ref(&mut codec),
            json!({"id": init["id"], "result": {}}),
        );
        let open = parse(&after_init.send[1]);

        let ready = feed(
            &mut codec,
            json!({"id": open["id"], "result": {"thread": {"id": "t"}}}),
        );
        let turn = parse(ready.send.last().expect("the held turn must be sent"));
        assert_eq!(turn["method"], "turn/start");
        assert_eq!(turn["params"]["input"][0]["text"], "hello");
    }

    fn codec_ref(codec: &mut CodexCodec) -> &mut CodexCodec {
        codec
    }

    #[test]
    fn resume_reopens_the_named_thread() {
        let mut codec = CodexCodec::new();
        let start = codec.start(&StartContext {
            cwd: r"C:\work".into(),
            resume: Some("thread-7".into()),
            model: None,
            effort: None,
        });
        let init = parse(&start.send[0]);
        let after = feed(&mut codec, json!({"id": init["id"], "result": {}}));
        let open = parse(&after.send[1]);
        assert_eq!(open["method"], "thread/resume");
        assert_eq!(open["params"]["threadId"], "thread-7");
    }

    #[test]
    fn deltas_pass_through_untouched_including_leading_spaces() {
        let mut codec = CodexCodec::new();
        handshake(&mut codec);

        let mut text = String::new();
        for chunk in ["Hello", ",", " lovely", " human", "."] {
            let step = feed(
                &mut codec,
                json!({"method": "item/agentMessage/delta",
                       "params": {"threadId": "thread-1", "delta": chunk}}),
            );
            match step.events.as_slice() {
                [SessionEvent::MessageDelta { text: t }] => text.push_str(t),
                other => panic!("expected one delta, got {other:?}"),
            }
        }
        assert_eq!(text, "Hello, lovely human.");
    }

    #[test]
    fn item_completed_is_the_authoritative_text() {
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "item/completed", "params": {"item": {
                "type": "agentMessage", "id": "m1", "text": "Hello, lovely human."}}}),
        );
        assert_eq!(
            step.events,
            vec![SessionEvent::MessageDone {
                text: "Hello, lovely human.".into()
            }]
        );
    }

    #[test]
    fn an_empty_agent_message_start_produces_nothing() {
        // `item/started` for an agentMessage carries an empty text.
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "item/completed", "params": {"item": {
                "type": "agentMessage", "text": ""}}}),
        );
        assert!(step.is_empty());
    }

    #[test]
    fn token_usage_reports_the_last_turn_not_the_running_total() {
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "thread/tokenUsage/updated", "params": {"tokenUsage": {
                "total": {"totalTokens": 999_999, "inputTokens": 999_999},
                "last": {"totalTokens": 16325, "inputTokens": 16316, "outputTokens": 9,
                         "cachedInputTokens": 12032, "reasoningOutputTokens": 0},
                "modelContextWindow": 258_400}}}),
        );
        match step.events.as_slice() {
            [SessionEvent::Usage(usage), SessionEvent::Context { used, window }] => {
                assert_eq!(usage.input_tokens, 16316, "must use `last`, not `total`");
                assert_eq!(usage.cache_read_tokens, 12032);
                assert_eq!(*used, Some(16325));
                assert_eq!(*window, Some(258_400));
            }
            other => panic!("unexpected events: {other:?}"),
        }
    }

    #[test]
    fn rate_limits_are_decoded_from_the_recorded_payload() {
        // Previously not handled at all, which is why switching from Claude to
        // Codex left Claude's numbers on screen.
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "account/rateLimits/updated", "params": {"rateLimits": {
                "limitId": "codex",
                "primary": {"usedPercent": 22, "windowDurationMins": 10080,
                            "resetsAt": 1_789_806_159},
                "secondary": null,
                "planType": "prolite"}}}),
        );
        match step.events.as_slice() {
            [SessionEvent::RateLimits { windows }] => {
                assert_eq!(windows.len(), 1, "a null window must not be reported");
                assert_eq!(windows[0].label, "7d");
                assert!((windows[0].utilization - 0.22).abs() < f64::EPSILON);
                assert_eq!(windows[0].resets_at_ms, Some(1_789_806_159_000));
            }
            other => panic!("unexpected events: {other:?}"),
        }
    }

    #[test]
    fn both_rate_limit_windows_are_reported_when_present() {
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "account/rateLimits/updated", "params": {"rateLimits": {
                "primary": {"usedPercent": 5, "windowDurationMins": 300},
                "secondary": {"usedPercent": 40, "windowDurationMins": 10080}}}}),
        );
        match step.events.as_slice() {
            [SessionEvent::RateLimits { windows }] => {
                assert_eq!(windows.len(), 2);
                assert_eq!(windows[0].label, "5h");
                assert_eq!(windows[1].label, "7d");
            }
            other => panic!("unexpected events: {other:?}"),
        }
    }

    #[test]
    fn turn_completed_ends_the_turn() {
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "turn/completed",
                   "params": {"turn": {"id": "t1", "status": "completed", "error": null}}}),
        );
        assert_eq!(
            step.events,
            vec![SessionEvent::TurnEnded {
                stop: StopReason::EndTurn
            }]
        );
    }

    #[test]
    fn an_aborted_turn_reads_as_cancelled() {
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "turn/completed", "params": {"turn": {"status": "aborted"}}}),
        );
        assert_eq!(
            step.events,
            vec![SessionEvent::TurnEnded {
                stop: StopReason::Cancelled
            }]
        );
    }

    #[test]
    fn a_failed_turn_carries_its_message() {
        let mut codec = CodexCodec::new();
        let step = feed(
            &mut codec,
            json!({"method": "turn/completed", "params": {"turn": {
                "status": "failed", "error": {"message": "model unavailable"}}}}),
        );
        assert!(matches!(
            step.events.first(),
            Some(SessionEvent::TurnEnded { stop: StopReason::Failed { message } })
                if message == "model unavailable"
        ));
    }

    #[test]
    fn cancel_interrupts_the_running_turn() {
        let mut codec = CodexCodec::new();
        handshake(&mut codec);
        feed(
            &mut codec,
            json!({"method": "turn/started", "params": {"turn": {"id": "turn-9"}}}),
        );

        let step = codec.cancel();
        let sent = parse(&step.send[0]);
        assert_eq!(sent["method"], "turn/interrupt");
        assert_eq!(sent["params"]["threadId"], "thread-1");
        assert_eq!(sent["params"]["turnId"], "turn-9");
    }

    #[test]
    fn cancelling_before_a_turn_starts_drops_the_queued_prompt() {
        let mut codec = CodexCodec::new();
        codec.start(&ctx());
        codec.send_turn("do not send me");
        assert!(codec.cancel().is_empty());
        assert!(
            codec.queued_turn.is_none(),
            "the queued prompt must be dropped"
        );
    }

    #[test]
    fn a_rejected_request_becomes_an_error_event() {
        let mut codec = CodexCodec::new();
        let start = codec.start(&ctx());
        let init = parse(&start.send[0]);
        let step = feed(
            &mut codec,
            json!({"id": init["id"], "error": {"code": -32600, "message": "not authenticated"}}),
        );
        assert!(matches!(
            step.events.first(),
            Some(SessionEvent::Error { error_kind, .. })
                if *error_kind == kitty_core::ErrorKind::Auth
        ));
    }

    #[test]
    fn garbage_is_ignored_rather_than_fatal() {
        let mut codec = CodexCodec::new();
        assert!(codec.on_frame("not json").is_empty());
        assert!(codec.on_frame("{}").is_empty());
        assert!(codec.on_frame(r#"{"method":"something/new"}"#).is_empty());
        assert!(codec.on_frame(r#"{"id":999,"result":{}}"#).is_empty());
    }
}
